@extends('user.base')

@section('content')
  <div class="inner-page-wrap">
    <div class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-md-offset-0 signup-view">
            <div class="col-md-6">
              <div class="signup-message">
                <div class="col-md-12">
                  <h3 class="text-left login-page">Privacy Policy</h3>
                  <div class="over-flow">
                    <p>Last Updated: March 28, 2015</p>
                    <p>Welcome to Annam! Protecting your privacy is really important to us. Accordingly, we’re providing this Privacy Policy to explain our practices regarding the collection, use, and disclosure of information that we receive when you use our Services. This Privacy Policy does not apply to any third-party websites, services, or applications, even if they are accessible through our Services. Any information that we collect is subject to the privacy policy in effect at the time that Information is collected. We may, however, modify and revise this Privacy Policy from time to time. If we make any material changes to this Privacy Policy, we’ll notify you of those changes by posting them on the Services or by sending you an email or other notification, and we’ll indicate when those changes will become effective. Finally, please note that, unless we define a term in this Privacy Policy, all capitalized words used in this Privacy Policy have the same meanings as in our Terms of Service.</p>
                    <h4>How We Collect and Use Information</h4>
                    <p>Our primary goals in collecting information are to provide and improve our Services, to administer your use of the Services (including your Account, if you are an Account holder), and to enable you to enjoy and easily navigate our Services. We also use some of your PII to contact you, as described in our Terms of Service. If you decide at any time that you no longer wish to receive such communications from us, please follow the unsubscribe instructions provided in the applicable communications. There are, however, some administrative communications that we have to send you from time to time, from which you cannot unsubscribe.</p>
                    <p><strong>Account Information.</strong> If you create an Account, we’ll collect certain information that can be used to identify you, such as your name, email address, postal address, phone number, and credit-card number or other billing information (“<strong>PII</strong>”). If you create an Account using your login credentials from one of your SNS Accounts, we’ll be able to access and collect your name and email address and other PII that your privacy settings on the SNS Account permit us to access. If you create an Account through the Site or one of your SNS Accounts, we may also collect your date of birth, ZIP code, and other information that is not considered PII because it can’t be used by itself to identify you. We don’t receive or store passwords for any of your SNS Accounts.</p>
                    <p><strong>Information Collected Using Cookies and other Web Technologies.</strong> Like many website and mobile-application operators, we use automated data collection tools such as Cookies and Web Beacons to collect certain information.</p>
                    <p><strong>“Cookies”</strong> are small text files that are placed on your hard drive by a Web server when you access our Services. We may use both session Cookies and persistent Cookies to identify that you’ve logged in to the Services and to tell us how and when you interact with our Services. We may also use Cookies to monitor aggregate usage and web traffic routing on our Services and to customize and improve our Services. Unlike persistent Cookies, session Cookies are deleted when you log off from the Services and close your browser. Although most browsers automatically accept Cookies, you can change your browser options to stop automatically accepting Cookies or to prompt you before accepting Cookies. Please note, however, that if you don’t accept Cookies, you may not be able to access all portions or features of the Services. Some third-party services providers that we engage (including third-party advertisers) may also place their own Cookies on your hard drive. Note that this Privacy Policy covers only our use of Cookies and does not include use of Cookies by such third parties.</p>
                    <p><strong>“Web Beacons”</strong> (also known as clear gifs or) are tiny graphics with a unique identifier that may be included on our Services for several purposes, including to deliver or communicate with Cookies, to track and measure the performance of our Services, to monitor how many visitors view our Services, and to monitor the effectiveness of our advertising. Unlike Cookies, which are stored on your hard drive, Web Beacons are typically embedded invisibly on web pages (or in an e-mail).</p>
                    <p><strong>Information Related to Use of the Services</strong>. Our servers automatically record certain information about how a person uses our Services (we refer to this information as “<strong>Log Data</strong>”), including both Account holders and non-Account holders (either, a “<strong>User</strong>”). Log Data may include information such as a User’s Internet Protocol address (“<strong>IP Address</strong>”), browser type, operating system, the web page that a User was visiting before accessing our Services, the pages or features of our Services to which a User browsed and the time spent on those pages or features, search terms, the links on our Services that a User clicked on, and other statistics. We use this information to administer the Services, and we analyze (and may engage third parties to analyze) this information to improve and enhance the Services by expanding their features and functionality and tailoring them to our Users’ needs and preferences. We use the IP Address to generate aggregate, non-identifying information about how our Services are used.</p>
                    <p><strong>Information Sent by Your Mobile Device.</strong> We collect certain information that your mobile device sends when you use our Services, such as a device identifier, user settings, and the operating system of your device, as well as information about your use of our Services.</p>
                    <p><strong>Location Information. </strong>In some cases we collect and store information about where you are located, such as by converting your IP address into a rough geolocation or through GPS or sensor data from your device that provides information on nearby Wi-Fi access points and cell towers to locate your mobile device. We may use location information to improve and personalize our Services for you. If you do not want us to collect location information, you can disable that feature on your mobile device.</p>
                    <h4>How We Share Information with Third Parties</h4>
                    <p>We will not share any PII that we have collected from you except as described below:</p>
                    <p><strong>Information Shared with Our Services Providers.</strong> We may engage third-party service providers to work with us to administer and provide the Services, such as to deliver Meals you order. Such third-party service providers have access to your PII only for the purpose of performing services on our behalf and are expressly obligated not to disclose or use your PII for any other purpose.</p>
                    <p><strong>Information Shared with Third Parties.</strong> We may share aggregated information and non-identifying information with third parties for industry research and analysis, demographic profiling, and other similar purposes.</p>
                    <p><strong>Information Disclosed in Connection with Business Transactions. </strong>Information that we collect from you, including PII, is considered to be a business asset. As a result, if we go out of business or enter bankruptcy or if we are acquired as a result of a transaction such as a merger, acquisition or asset sale, your PII may be disclosed or transferred to the third-party acquirer in connection with the transaction.</p>
                    <p><strong>Information Disclosed for Our Protection and the Protection of Others.</strong> We cooperate with government and law enforcement officials or private parties to enforce and comply with the law. We may disclose any information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate: (i) to respond to claims, legal process (including subpoenas); (ii) to protect our property, rights and safety and the property, rights and safety of a third party or the public in general; and (iii) to stop any activity that we consider illegal, unethical or legally actionable activity.</p>
                    <p><strong>Information We Disclose With Your Consent or at Your Request.</strong> We will share your PII with third-party sites or platforms, such as social networking sites, if you have expressly requested that we do so.</p>
                    <h4>Security of Your Information</h4>
                    <p>We take reasonable measures to protect the information that we collect from or about you (including your PII) from unauthorized access, use, or disclosure. Please be aware, however, that no method of transmitting information over the Internet or storing information is completely secure. Accordingly, we can’t guarantee the absolute security of any information.</p>
                    <p>Identity theft and “phishing” are of great concern to us. Safeguarding your information to help protect you is a top priority for us. We won’t ever request any PII from you through unsolicited emails, text messages, or phone calls, so please don’t try to provide your PII to us except through our official Site and Apps. If you suspect someone is trying to obtain your PII by impersonating us or misleading you or other members of our community about the suspect person’s relationship to us or to our Services, please contact us at support@annam.com.</p>
                    <h4>Links to Other Sites</h4>
                    <p>Our Services may contain links to other websites and services. Any information that you provide on or to a third-party website or service is provided directly to the owner of the website or service and is subject to that party’s privacy policy. Our Privacy Policy does not apply to such websites or services, and we’re not responsible for the content, privacy or security practices and policies of those websites or services. To protect your information we recommend that you carefully review the privacy policies of other websites and services that you access.</p>
                    <h4>Modifying Your Information</h4>
                    <p>You can access and modify the PII associated with your Account by changing it in your Account profile. If you want us to delete your PII and your Account, please contact us at support@annam.com with your request. We’ll take steps to delete your information as soon as is practicable, but some information may remain in archived/backup copies for our records or as otherwise required by law.</p>
                    <h4>International Transfer</h4>
                    <p>Your PII may be transferred to, and maintained on, computers located outside of your state, province, country or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction. If you’re located outside the United States and choose to provide your PII to us, we may transfer your PII to the United States and process it here.</p>
                    <h4>Our Policy Toward Children</h4>
                    <p>Our Services are not directed to children under 13, and we do not knowingly collect PII from children under 13. Children under 13 are not permitted to use our Services, and if we learn that we have collected PII of a child under 13, we will take steps to delete such information from our files as soon as possible.</p>
                    <h4>Questions?</h4>
                    <p>Please contact us at <a class="clr" href="mailto:info@annamhomelyfood.com">info@annamhomelyfood.com</a> if you have any questions about our Privacy Policy.</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="height"></div>
            <div class="col-md-6">
              <div class="signup-message">
                <div class="col-md-12">
                  <h3 class="text-left login-page">Terms of Service</h3>
                  <div class="over-flow">
                    <p>Last Updated: March 28, 2015</p>
                    <p>Welcome to Annam, located at <a class="clr" href="http://annamhomelyfood.com/">annamhomelyfood.com</a> (our “<strong>Site</strong>”)! Please read these Terms of Use (these “<strong>Terms</strong>”) carefully because they govern your use of our Site, our mobile application (our “<strong>App</strong>”), and the other services we provide via our Site and App (our Site, our App, and our other services will be referred to as the “<strong>Services</strong>”).</p>
                    <h4>Agreement to Terms</h4>
                    <p>By using our Services, you agree to be bound by these Terms. If you don’t agree to these Terms, do not use the Services. If you are accessing and using the Services on behalf of a company (such as your employer) or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms. In that case, “you” and “your” will refer to that company or other legal entity.</p>
                    <h4>Changes to Terms or Services</h4>
                    <p>We may modify these Terms at any time, in our sole discretion. If we do so, we’ll let you know either by posting the modified Terms on the Site, in our App, or through other communications. It’s important that you review the Terms whenever we modify them because if you continue to use the Services after we have posted modified Terms on the Site or in our App or have communicated them to you, you are indicating to us that you agree to be bound by the modified Terms. If you don’t agree to be bound by the modified Terms, then you can’t use the Services anymore. Because our Services are evolving over time we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.</p>
                    <h4>Who May Use the Services</h4>
                    <p><strong>Eligibility</strong></p>
                    <p>You may use the Services only if you are at least 18 years old and capable of forming a binding contract with Annam and are not barred from using the Services under applicable law.  If you’re under 18 years old, you may not use any of our Services.</p>
                    <p><strong>Registration and Your Information</strong></p>
                    <p>If you want to use certain features of the Services you’ll have to create an account (“<strong>Account</strong>”). You can do this on our Site, in our App, or through your account with certain third-party social networking services, such as Facebook or Twitter (each, an “<strong>SNS Account</strong>”). If you choose the SNS Account option, we’ll create your Account by extracting from your SNS Account certain personal information, such as your name, email address, and other personal information that your privacy settings on the SNS Account permit us to access.</p>
                    <p>It’s important that you provide us with accurate, complete, and up-to-date information for your Account, so you agree to update such information, as needed, to keep it accurate, complete, and up-to-date. If you don’t, we might have to suspend or terminate your Account. You agree that you won’t disclose your Account password to anyone and that you’ll notify us immediately of any unauthorized use of your Account. You’re responsible for all activities that occur under your Account, whether or not you know about them, so please keep your password secret and secure.</p>
                    <p>We want to keep all our users safe and happy, so we reserve the right, in our sole discretion, to disable, suspend, cancel, or delete any Account for any reason, or to refuse any user access to any of our Services, if we think doing so will help keep things safe and enjoyable for everybody.</p>
                    <h4>Privacy Policy</h4>
                    <p>Please refer to our <a class="clr" href="http://annamhomelyfood.com/privacy-and-terms-of-service/"> Privacy Policy</a> for information on how we collect, use, and disclose your information.</p>
                    <h4>The Services</h4>
                    <p>We provide a platform through which users can buy quality meals and food items (the “<strong>Meals</strong>”) at fixed prices. We want you to love not just the Meals you find on our Site and in our App but also the whole experience you get from using our Services. We’re confident that you’ll love Annam, but please understand that you use our Services at your own risk. You agree to hold us, as well as our officers, directors, agents, subsidiaries, joint venturers, and employees (jointly and severally, our “<strong>Affiliates</strong>”) not liable, to the full extent permissible under all applicable law, for any harm, loss, or damage that may come to you or to anyone else as a consequence of your use of our Services.</p>
                    <p>When you buy a Meal through any of our Services (such purchase, a “<strong>Transaction</strong>”), we may ask you to supply additional information relevant to your Transaction, including, without limitation, your credit-card number, the expiration date of your credit card, and your address(es) for billing and delivery (such information, “<strong>Payment Information</strong>”). You represent and warrant that you have the legal right to use all payment method(s) represented by any such Payment Information, whether you provide it in the course of a Transaction or in connection with your Account. When you initiate a Transaction, you authorize us to provide your Payment Information to third parties so we can complete your Transaction; you may need to provide additional information to verify your identity before completing your Transaction (such information is included within the definition of Payment Information).</p>
                    <p>All sales are final.  But if something unexpected happens in the course of fulfilling your order, we reserve the right to cancel your order for any reason; if we cancel your order, we’ll refund any payment you may already have remitted to us.</p>
                    <p>We make a conscientious effort to describe and display every Meal accurately on our Site and in our App. Because all our Meals are handcrafted by excellent chefs, however, occasionally a Meal you receive won’t look or taste exactly as it was described or depicted to you. You understand that this is normal, and you agree to accept such a Meal, regardless of reasonable variation from its description or depiction. We can’t and don’t guarantee the accuracy or completeness of any description or depiction of any Meal. We reserve the right to change or update any such description or depiction and to correct errors, inaccuracies, or omissions at any time without giving you notice.</p>
                    <p>We can’t guarantee that every Meal will arrive exactly within the timeframe we give you when you initiate a Transaction. If a Meal arrives early or late, you agree that you will still accept the Meal and release us from all liability for any loss, damage, or inconvenience that you encounter as a result of early or late delivery.</p>
                    <p>If you have a complaint or dispute concerning a Meal you’ve purchased through our Services, please contact us, and we’ll try to fix the problem in the manner we deem appropriate, in our discretion.</p>
                    <h4>Feedback</h4>
                    <p>We welcome feedback, comments, and suggestions for improvements to our Services (“<strong>Feedback</strong>”). You can submit Feedback by emailing us at support@annam.com. You grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable, and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon, and otherwise exploit the Feedback for any purpose.</p>
                    <h4>Content and Content Rights</h4>
                    <p>For purposes of these Terms, “<strong>Content</strong>” means text, graphics, images, music, software, audio, video, works of authorship of any kind, and information or other materials that are posted, generated, provided, or otherwise made available through the Services.</p>
                    <h4>Content Ownership, Responsibility, and Removal</h4>
                    <p>We don’t claim any ownership rights in any Content that you make available through the Services, and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit your User Content. Subject to the foregoing, we and our licensors exclusively own all right, title, and interest in and to the Services, including all associated intellectual-property rights. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary-rights notices incorporated in or accompanying our Services or any Content.</p>
                    <p><strong>Your Rights in Our Content</strong></p>
                    <p>Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, non-sublicenseable license to access and view the Content solely in connection with your permitted use of our Services and solely for your personal and non-commercial purposes.</p>
                    <h4>General Prohibitions and Our Enforcement Rights</h4>
                    <p>You agree not to do any of the following:</p>
                    <ol class="numbers">
                      <li>Use, display, mirror, or frame (i) our Site or App or any individual element within our Site, Services, or App; (ii) Annam’s name or any Annam trademark, logo, or other proprietary information; (iii) the layout and design of any page or form contained on a page without Annam’s express written consent;</li>
                      <li>Access, tamper with, or use non-public areas of the Site or App, Annam’s computer systems, or the technical delivery systems of Annam’s providers;</li>
                      <li>Attempt to probe, scan, or test the vulnerability of any Annam system or network or breach any security or authentication measures;</li>
                      <li>Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Annam or any of Annam’s providers or any other third party (including another user) to protect the Site, App, Services, or any of their Content;</li>
                      <li>Attempt to access or search the Site, App, Services, or any of their Content or download any Content from them through the use of any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, data-mining tools, and the like) other than the software or search agents provided by us or other generally available third-party web browsers;</li>
                      <li>Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters, or other form of solicitation;</li>
                      <li>Use any meta tags or other hidden text or metadata utilizing a Annam trademark, logo URL, or product name without our express written consent;</li>
                      <li>Use the Site, App, Services, or any of their Content for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms;</li>
                      <li>Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting or in any way use the Site, App, Services, or any of their Content to send altered, deceptive, or false source-identifying information;</li>
                      <li>Attempt to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Site, App, Services, or any of their Content;</li>
                      <li>Interfere with, or attempt to interfere with, the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Site, App, or Services;</li>
                      <li>Collect or store any personally identifiable information from the Site, App, or Services from any other user without the user’s express permission;</li>
                      <li>Impersonate or misrepresent your affiliation with any person or entity;</li>
                      <li>Violate any applicable law or regulation; or</li>
                      <li>Encourage or enable any other individual to do any of the foregoing.</li>
                    </ol>
                    <p>Although we’re not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>
                    <p>We’re not responsible for the availability of outside websites or resources linked from our Site or our App. We don’t endorse and aren’t responsible or liable for any content, advertisements, products, or other materials on or available from such websites or resources. You understand and agree that we won’t be responsible or liable, directly or indirectly, for any damage or loss caused, or alleged to be caused, by or in connection with the use of or reliance on any such content, goods, or services available on or through any such third-party websites or resources.</p>
                    <h4>App Policies</h4>
                    <p>Subject to your compliance with these Terms, we grant you a limited non-exclusive, non-transferable, non-sublicenseable license to download and install a copy of our App on a mobile device or computer that you own or control and to run such copy of the App solely for your own personal non-commercial purposes. You may not copy our App, except to make a reasonable number of copies for backup or archival purposes. Except as expressly permitted in these Terms, you may not: (i) copy, modify, or create derivative works based on the App; (ii) distribute, transfer, sublicense, lease, lend, or rent the App to any third party; (iii) reverse engineer, decompile, or disassemble the App; or (iv) make the functionality of the App available to multiple users through any means. We reserve all rights in and to the App not expressly granted to you under these Terms.</p>
                    <p>If you access or download our App from the Apple Store, then you agree to use the App only (i) on an Apple-branded product or device that runs iOS (Apple’s proprietary operating system software) and (ii) as permitted by the “Usage Rules” set forth in the Apple Store Terms of Service.</p>
                    <p>If you accessed or downloaded our App from any app store or distribution platform (such as the Apple Store, Google Play, and the Amazon Appstore) (each, an “<strong>App Provider</strong>”), then you acknowledge and agree that:</p>
                    <ol class="numbers">
                      <li>These Terms are concluded between you and us, and not with App Provider, and, as between Annam and the App Provider, Annam is solely responsible for the App.</li>
                      <li>App Provider has no obligation to furnish any maintenance and support services with respect to the App.</li>
                      <li>In the event of any failure of the App to conform to any applicable warranty, you may notify App Provider and App Provider will refund the purchase price for the App to you (if applicable) and, to the maximum extent permitted by applicable law, App Provider will have no other warranty obligation whatsoever with respect to the App. Any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure of an App to conform to any warranty will be the sole responsibility of Annam.</li>
                      <li>App Provider is not responsible for addressing any claims you have or any claims of any third party relating to the App or your possession and use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</li>
                      <li>In the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual-property rights, Annam will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual-property infringement claim to the extent required by these Terms.</li>
                      <li>App Provider and its subsidiaries are third-party beneficiaries of these Terms as related to your license of the App, and, upon your acceptance of the terms and conditions of these Terms, App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the App against you as a third-party beneficiary.</li>
                      <li>You must comply with all applicable third-party terms of service when using the App.</li>
                      <li>You will comply with all U.S. and foreign export laws and regulations to ensure that neither the App nor any technical data related thereto nor any direct product thereof is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations, and you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a “terrorist supporting” country. You are not listed on any U.S. Government list of prohibited or restricted parties.</li>
                    </ol>
                    <h4>Termination</h4>
                    <p>We may terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. You may cancel your Account at any time by sending an email to us at support@annam.com. Upon any termination, discontinuation, or cancellation of Services or your Account, the following Terms will survive: content ownership, warranty disclaimers, limitations of liability, and dispute resolution.</p>
                    <h4>Warranty Disclaimers</h4>
                    <p>THE SERVICES AND MEALS ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We make no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness or reliability of any Content.</p>
                    <h4>Indemnity</h4>
                    <p>You will indemnify and hold harmless Annam and our officers, directors, employee, and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (i) your access to or use of the Services or (ii) your violation of these Terms.</p>
                    <h4>Limitation of Liability</h4>
                    <p>NEITHER WE NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES OR MEALS WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES OR CONSUMPTION OF MEALS, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
                    <p>IN NO EVENT WILL OUR TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, FROM THE USE OF OR INABILITY TO USE THE SERVICES, OR FROM ANY MEALS YOU HAVE RECEIVED EXCEED THE AMOUNTS YOU HAVE PAID TO MUNCHERY FOR USE OF THE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO US, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND US.</p>
                    <p>THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND US.</p>
                    <h4>Dispute Resolution</h4>
                    <p><strong>Governing Law</strong></p>
                    <p>These Terms and any action related to them will be governed by the laws of the State of California without regard to its conflict of laws provisions.</p>
                    <p><strong>Agreement to Arbitrate</strong></p>
                    <p>You and we agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services or Content (collectively, “<strong>Disputes</strong>”) will be settled by binding arbitration, except that each party retains the right: (i) to bring an individual action in small claims court and (ii) to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights (the action described in the foregoing clause (ii), an “<strong>IP Protection Action</strong>”). The exclusive jurisdiction and venue of any IP Protection Action will be the state and federal courts located in the Northern District of California and each of the parties hereto waives any objection to jurisdiction and venue in such courts. You acknowledge and agree that you and we are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and we otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.</p>
                    <p><strong>Arbitration Rules</strong></p>
                    <p>The arbitration will be administered by the American Arbitration Association (“<strong>AAA</strong>”) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the “<strong>AAA Rules</strong>”) then in effect, except as modified by this “Dispute Resolution” section. (The AAA Rules are available or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.</p>
                    <p><strong>Arbitration Process</strong></p>
                    <p>A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration and a separate form for California residents. The arbitrator will be either a retired judge or an attorney licensed to practice law and will be selected by the parties from the AAA’s roster of arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</p>
                    <p><strong>Arbitration Location and Procedure</strong></p>
                    <p>Unless you and we otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of the documents that you and we submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</p>
                    <p><strong>Arbitrator’s Decision</strong></p>
                    <p>The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator’s award of damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant’s individual claim. If you prevail in arbitration you will be entitled to an award of attorneys’ fees and expenses, to the extent provided under applicable law. We will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys’ fees and expenses if it prevails in arbitration.</p>
                    <p><strong>Fees</strong></p>
                    <p>Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules. However, if your claim for damages does not exceed $75,000, we will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)).</p>
                    <p><strong>Changes</strong></p>
                    <p>Notwithstanding the provisions of the section, above, concerning changes to these Terms or to the Services, if we change this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to www.Annam.com) within 30 days of the date such change became effective, as indicated in the “Last Updated” date above or in the date of our email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and we in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
                    <h4>General Terms</h4>
                    <p>These Terms constitute the entire and exclusive understanding and agreement between you and us regarding the Services and Content, and these Terms supersede and replace any and all prior oral or written understandings or agreements between you and us regarding the Services and Content. If for any reason a court of competent jurisdiction or an arbitrator finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
                    <p>You may not assign or transfer these Terms, by operation of law or otherwise, without our prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. We may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
                    <p>Any notices or other communications provided by us under these Terms, including those regarding modifications to these Terms, will be given: (i) by us via email; or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
                    <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of us. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</p>
                    <h4>Contact Information</h4>
                    <p>If you have any questions about these Terms or the Services, please contact us at <a class="clr" href="mailto:info@annamhomelyfood.com">info@annamhomelyfood.com</a>.</p>
                    <p>The services hereunder are offered by Annam Inc., located at bangalore madiwala.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- //row --> 
      </div>
      <!-- //container --> 
    </div>
  </div>
@stop
